service: sls-my-first-lamba

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 128
  timeout: 3

functions:
  index:
    handler: index.handler
    description: My first lamba example
    events:
      - http:
          path: /
          method: get
          cors: true